deploy_path: "_site"
host: http://rockymeza.com
rename_extensions:
  .jinja: .html
  .md: .html
dont_process: CNAME
meta:
  title: rockymeza.com
extensions:
  - extensions.markdown2_extension.Markdown2Extension
filters:
  date: extensions.date_extension.date
  markdown2: extensions.markdown2_extension.markdown2
processors:
  - processors.image
  - processors.categories
