deploy_path: "_site"
host: http://rockymeza.com
rename_extensions:
  .jinja: .html
  .md: .html
meta:
  title: rockymeza.com
extensions:
  - strange_case.extensions.Markdown2Extension
filters:
  date: strange_case.extensions.date
  markdown2: strange_case.extensions.markdown
processors:
  - strange_case.extensions.image_processor
  - strange_case.extensions.category_processor
