deploy_path: "_site"
remove_stale_files: true
dont_remove: ['*_site/static/*']
host: http://rockymeza.com
rename_extensions:
  .jinja: .html
  .md: .html
meta:
  title: rockymeza.com
extensions:
  - strange_case.extensions.markdown.MarkdownExtension
filters:
  date: strange_case.extensions.date.date
  markdown: strange_case.extensions.markdown.markdown
processors:
  - strange_case.extensions.image
  - strange_case.extensions.category
  - strange_case.extensions.scss_ext
